### ISSUE TITLE
No Fille or directory 

### ISSUE THREAD

**Issue by Y02himitsu** [kamil-cias/niffler#1]
executing the niffler command generates an error

/usr/bin/niffler: line 1: "/.ssh/authorized_keys": No such file or directory
/usr/bin/niffler: line 1: payload:allShortcutsEnabled:false: command not found

even when I'm in the .ssh directory

**Comment by kamil-cias** [comment]
The solution to the problem was to add a check whether the $home variable is not empty and whether the $home variable is not equal to the system root directory (/). The following instruction fragment solved the problem.

`if [[ -n "$home" && "$home" != "/" && -f "$home/.ssh/authorized_keys" ]]; then`

**Comment by kamil-cias** [comment]
Solved
